In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customer.csv')

In [4]:
df.sample(5)

age  gender   review education purchased
35   74    Male     Poor    School       Yes
11   74    Male     Good        UG       Yes
20   57  Female  Average    School       Yes
34   86    Male  Average    School        No
44   77  Female  Average        UG        No

In [7]:
df = df.iloc[:,2:]

In [8]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:, 0:2],df.iloc[:,-1],test_size = 0.2)

In [13]:
X_train

review education
16     Poor        UG
2      Good        PG
43     Poor        PG
26     Poor        PG
3      Good        PG
1      Poor        UG
34  Average    School
39     Poor        PG
9      Good        UG
6      Good    School
49     Good        UG
7      Poor    School
21  Average        PG
29  Average        UG
45     Poor        PG
41     Good        PG
20  Average    School
31     Poor    School
22     Poor        PG
8   Average        UG
24  Average        PG
17     Poor        UG
30  Average        UG
40     Good    School
46     Poor        PG
5   Average    School
33     Good        PG
42     Good        PG
25     Good    School
28     Poor    School
18     Good    School
11     Good        UG
47     Good        PG
36     Good        UG
38     Good    School
14     Poor        PG
15     Poor        UG
35     Poor    School
4   Average        UG
10     Good        UG

In [14]:
y_train

16    Yes
2      No
43     No
26     No
3      No
1      No
34     No
39     No
9     Yes
6      No
49     No
7     Yes
21     No
29    Yes
45    Yes
41    Yes
20    Yes
31    Yes
22    Yes
8      No
24    Yes
17    Yes
30     No
40     No
46     No
5     Yes
33    Yes
42    Yes
25     No
28     No
18     No
11    Yes
47    Yes
36    Yes
38     No
14    Yes
15     No
35    Yes
4      No
10    Yes
Name: purchased, dtype: object

In [15]:
X_test

review education
27     Poor        PG
0   Average    School
19     Poor        PG
13  Average    School
12     Poor    School
32  Average        UG
44  Average        UG
48     Good        UG
37  Average        PG
23     Good    School

In [16]:
y_test

27     No
0      No
19    Yes
13     No
12     No
32    Yes
44     No
48    Yes
37    Yes
23     No
Name: purchased, dtype: object

In [17]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [18]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [19]:
X_train = oe.transform(X_train)
X_train

array([[0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.]])

In [20]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [21]:
X_train

array([[0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.]])

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [23]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [24]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1])